### ISSUE TITLE
Latest MacOS Update Thwarts novafix?

### ISSUE THREAD

**Issue by finemalbec** [RyuKojiro/novafix#11] opened 2016-12-28 05:34 UTC
The updates I installed yesterday (10.12.2) seem to thwart this fix. The icon bounces in the dock for a few seconds before simply disappearing. No error message pops up.

**Comment by RyuKojiro** [comment] 2016-12-28 23:37
I don't have a machine that I can test this on right now, since I'm traveling. What output do you get if you run the launcher in a terminal, rather than just launching the application?

**Comment by finemalbec** [comment] 2016-12-30 00:46
Thanks for the quick reply. It gives me fork: Resource temporarily
unavailable

Tried with a couple of other apps open, then again as the first thing after
restart.

**Comment by RyuKojiro** [comment] 2017-01-05 04:29
That's odd. The launcher doesn't spawn any sub shells, so either your shell is broken, something else inside EV is broken, or your system actually is experiencing resource starvation. I updated a machine to 10.12.2 and couldn't reproduce your issue; it just worked as expected.

What do you get when you run the EV binary directly, but from a terminal? (Should be something like /Applications/EV\ Nova.app/Contents/MacOS/EV\ Nova.original if you've installed novafix inside the app bundle.)

**Comment by whosawhatsis** [comment] 2017-01-22 07:59
I'm on 10.12.2 as well. I'm getting "EV Nova quit unexpectedly". Launching from the terminal gives this output:

dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

/Applications/EV Nova.app/Contents/MacOS/Ev Nova: line 13: 87080 Abort trap: 6           "$WD/$EVBIN.original"

**Comment by RyuKojiro** [comment] 2017-01-29 06:29
This is another GLEngine issue. The library may have moved in the update, and the GLEngine stuff that was added to the launcher should never really have been necessary. Can you try removing the following lines from the launcher and see if that fixes it?
```
if [ -e $GLENGINE ]
then
	export DYLD_INSERT_LIBRARIES="$DYLD_INSERT_LIBRARIES:$GLENGINE"
fi
```

**Comment by smitty006** [comment] 2017-02-07 23:59
I'm having the same issue as whosawhatsis but I'm running 10.12.3
Almost the exact same thing through the terminal 
dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

/Applications/EV Nova.app/Contents/MacOS/Ev Nova: line 13:  5815 Abort trap: 6           "$WD/$EVBIN.original"

I only used the quick installer to patch the fix, since i'm a bit of a coding neophyte but if there is anything I can test I'm willing to help.

**Comment by RyuKojiro** [comment] 2017-02-14 01:19
Could you test removing the GLENGINE lines that I mentioned above, and let me know if it still happens?

**Comment by pinskerj** [comment] 2017-02-22 19:36
I tried that and reran make on the terminal, then ran ./launcher.sh but it does not work, get terminal error:

dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

./launcher.sh: line 15: 15182 Abort trap: 6           "${EVROOT}/${EVBIN}"

**Comment by RyuKojiro** [comment] 2017-02-23 18:51
Just `make`? Or `make install`?

**Comment by RyuKojiro** [comment] 2017-02-26 01:16
Can you run this in a terminal and paste the output?
`nm /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine | grep _gliCreateContextWithShared`

**Comment by RyuKojiro** [comment] 2017-02-26 01:18
Also, how quickly does it crash? Is it immediately upon running, without any sign of the app running? Or does EV get a chance to do anything video related?

**Comment by pinskerj** [comment] 2017-02-27 16:43
On Mac OS 10.12.3 I get the output:

0000000000000fc8 T _gliCreateContextWithShared

EV Nova quites immediately upon loading, no black screen, nothing. No sign the app is running.

**Comment by RyuKojiro** [comment] 2017-03-06 03:53
That's extremely odd. You've got the framework, it's exactly where dyld expects it, and it's got the symbol it is looking for. I'm not seeing why it's failing.

**Comment by kurtbp587** [comment] 2017-03-19 16:46
I used the installer earlier in the week and it worked great.  Thanks so much for doing this - i'm glad I can play EVN again.  However, it looks like the installer is no longer available on dropbox.  Any chance it will come back shortly?  Thanks so much!

**Comment by RyuKojiro** [comment] 2017-03-19 22:41
I'm glad you enjoy it! I've fixed the installer link in the README to point to a gist (that shouldn't ever break). However, this issue is about GLEngine not working. Next time just message me directly or open a separate issue.

**Comment by RyuKojiro** [comment] 2017-03-20 04:33
Great news, I was able to reproduce this issue! (for a short time)

Try undoing the GLENGINE changes I asked you to make, then run `make uninstall`, `make clean`, and finally `make install` again.

Let me know if that fixes it.

**Comment by pinskerj** [comment] 2017-03-20 21:30
No luck there. Still just immediately crashes/quits app. Perhaps I did something wrong but I do not think so.

**Comment by RyuKojiro** [comment] 2017-03-21 06:06
Hmm, weird. I am wondering if this has something to do with dyld's cache being broken for the launcher. I was able to reproduce the issue after traversing an update, but accidentally fixed it through something along the lines of what I described above. Can you try running `update_dyld_shared_cache` and then see if the launcher works (or the EV app if you've installed the launcher)?

**Comment by pinskerj** [comment] 2017-03-21 16:25
Sorry, even after doing this it still does not work.

**Comment by RyuKojiro** [comment] 2017-03-22 04:15
Okay, the last thing that I can think to try (based on what fixed it for me):
1) `make uninstall`
2) Run the EV app, and let it crash as it used to
3) `make install`
and then see if it runs.

If this doesn't work, I'm going to try and get a VM running with an older OS X, update it, and get the issue reproducing again.

**Comment by pinskerj** [comment] 2017-03-26 16:56
I am now getting the resource errors mentioned above, so I do not think this worked. Sorry.

**Comment by RyuKojiro** [comment] 2017-04-04 01:50
I'm wondering if that fixed the GLENGINE issue, and that the fork error is something separate. Hopefully someone else can confirm that fixing the GLENGINE issue for them.

Can you try changing lines 16 through 18 to be this (adding the exec at the beginnings):
```
	exec "$WD/$EVBIN.original"
else
	exec "/Applications/EV Nova.app/Contents/MacOS/$EVBIN"
```

That will prevent EV from being forked as a separate process, and might fix your new issue. If so, I can add that fix to the launcher, and add a fix for the GLENGINE issue, too.

**Comment by RyuKojiro** [comment] 2017-05-11 05:18
I'm going to close this issue until I have any sort of feedback that it either did or didn't work.

**Closed as completed by RyuKojiro** 2017-05-11 05:18 UTC

**Comment by pinskerj** [comment] 2017-05-14 00:39
Daniel, I can confirm with your latest exec instruction, I have the game running on a system with 10.12, thank you!

**Comment by simX** [comment] 2017-06-05 16:53
FYI, I was having this problem on 10.12.5, and running update_dyld_shared_cache fixed the problem.

**Comment by RyuKojiro** [comment] 2017-06-07 06:28
I'm glad you mentioned that. This pretty much confirms my suspicions. I'm working on a way to have this keep work across updates without having to take action, but reproducing it is a PITA.
