### ISSUE TITLE
Mojave again

### ISSUE THREAD

**Issue by DrLex0** [RyuKojiro/novafix#14] opened 2019-01-19 19:25 UTC
I have been trying to get EVN running on my new MacBook Pro that is running 10.14.2, but everything I have tried so far has failed (except running it in Boot Camp, but I would like to avoid having to do that).

With the launcher.sh, I get:
```
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.200.3/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

Abort trap: 6
```

Running the patched app itself shows the same _gliCreateContextWithShared error.
The AppleFSCompression errors seem to be [irrelevant](https://groups.google.com/forum/#!topic/bbedit/MMTDbqDMNeQ).

I have verified with `nm` that the symbol *is* in the GLEngine framework.

I have tried the workarounds mentioned in #11 of running `sudo update_dyld_shared_cache` and letting the original app crash and then running the patched app, but this makes no difference.

I have also tried this trick which I found elsewhere: before invoking launcher.sh, execute `export DYLD_INSERT_LIBRARIES='/System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine' `
But it doesn't work either.

It seems other people are able to run EVN in Mojave, why does it fail on my system?
 

(By the way, you can enter your license code if you still know when you bought the game. Set your clock to 1 day after the date you received the code, and it will work. Normally you would need to do this offline but since the Ambrosia licensing server is dead, this no longer matters.)

**Comment by kael131** [comment] 2019-04-07 15:01
So I just wanted to let you know that I managed to fix my Mojave 10.14.4 issue using the solution in #12.

The auto-installer might be using an older version of the code. I did a fresh clone of the repo, make uninstall, make install and it works now.

**Comment by RyuKojiro** [comment] 2019-04-08 02:52
@kael131, that's a great point.
@DrLex0, you are building and installing fresh, not using the .pkg, right?

If you are using the .pkg, I can rebuild and reupload it.

**Comment by DrLex0** [comment] 2019-04-08 08:33
I have tried everything and I have given up, I now play EV Nova under SheepShaver. The OS X native app won't work in the upcoming major OS X release anyway.

**Comment by pinskerj** [comment] 2020-05-13 00:59
It works great under Mojave. I don't know if the auto install pkg has the latest fixes, but if you do the make install method from the terminal as described in the link to #12 above it works great under mojave. I just did this and now the game plays fine.

**Comment by RyuKojiro** [comment] 2020-07-07 17:39
Unless anyone has any other useful information that can help me determine the cause, I'm gonna close this issue.

**Comment by pinskerj** [comment] 2020-07-07 17:56
I think the issue may be people are running it without the latest code fix. So it can all be in one spot, here is how I did the patch in Mojave and it works great:

1) Run a clean copy of EV Nova, let it crash.
2) Open terminal, CD to to your folder with NovaFix
3) The code for launcher.sh should be the latest bug fix version, which is this:

#!/bin/sh
WD=`dirname "$0"`
EVBIN="Ev Nova"
GLENGINE="/System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine"

export DYLD_FORCE_FLAT_NAMESPACE=1
export DYLD_INSERT_LIBRARIES="$WD/libNova.A.dylib"

if [ -e $GLENGINE ]
then
	export DYLD_INSERT_LIBRARIES="$DYLD_INSERT_LIBRARIES:$GLENGINE"
fi

if [ -e "$WD/$EVBIN.original" ]
then
	exec "$WD/$EVBIN.original"
else
	exec "/Applications/EV Nova.app/Contents/MacOS/$EVBIN"
fi

4) Run `make`
5) Run `./launcher.sh` 

You are probably using a slightly older version of launcher.sh that is why it did not work in Mojave. I have attached a copy of the file here (unzip it first) that I used and it worked great.

[launcher.sh.zip](https://github.com/RyuKojiro/novafix/files/4886384/launcher.sh.zip)

**Closed as completed** 2021-12-31 22:59 UTC
